webapp/config/routes.rb
WindosorFrontend::Application.routes.draw do

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  devise_for :users

  resources :users, except: [:show, :new] do
    collection do
      get 'edit_account'
      put 'update_account'
    end
  end

  resources :groups, except: [:new] do
    collection do
      get :tickers
    end
  end

  resources :companies do
    collection do
      get   :delete_info
      get   :delete_db
      post  :destroy_top5
      post  :destroy_bod
      post  :destroy_db
      post  :destroy_peers
    end
  end

  # Search
  get "search/quick_search",  as: :quick_search
  get "search/filter_recent_search", as: :filter_recent_search
  get "search/full_search",   as: :full_search
  get "search/recent_search/:id", to: "search#recent_search", as: :top_5_recent_search
  get "search/search_log/:id", to: "search#search_log", as: :search_log


  post "search/results",      as: :search_result
  post "search/download",     as: :file_download
  post "search/group_search", as: :group_search

  # Files Upload
  get   "files/upload",       as: :file_upload
  post  "files/send_file",    as: :send_file

  # Company Peers
  get 'company_peers', to: 'company_peers#company_peers'
  get 'incoming_peers',        to: 'company_peers#incoming_peers'
  get 'peers_peers',        to: 'company_peers#peers_peers'
  post 'company_peers/incoming_peers_result', as: :incoming_peers_result
  post 'company_peers/peers_peers_single_ticker_result', as: :peers_peers_single_ticker_result
  post 'company_peers/peers_peers_ticker_list_result', as: :peers_peers_ticker_list_result

  # Export Files
  post 'companies/peers_inventory_file',     as: :export_peers_inventory
  post 'companies/companies_inventory_file', as: :export_companies_inventory

  post 'company_peers/peers_peers_single_ticker_file', as: :export_peers_peers_single_ticker
  post 'company_peers/peers_peers_ticker_list_file', as: :export_peers_peers_ticker_list
  post 'company_peers/peers_peers_raw_data_file', as: :export_peers_peers_raw_data
  post 'company_peers/peers_peers_raw_data_file_from_primary', as: :export_peers_peers_raw_data_from_primary

  post 'company_peers/incoming_peers_raw_data_file', as: :export_incoming_peers_raw_data

  # Upload Log
  get "upload_log/audit", as: :audit_log
  get "upload_log/search", as: :search_upload_log
  get "upload_log/upload_log_file", as: :export_upload_log

end

webapp/app/models/upload_log.rb
# == Schema Information
#
# Table name: upload_logs
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  upload_type :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class UploadLog < ActiveRecord::Base
  extend JSONLoadable

  attr_accessible :upload_type, :user, :detail_upload_files
  belongs_to :user
  has_many :detail_upload_files

  scope :with_ticker, lambda { |value| joins(:detail_upload_files).where('ticker = ?', value) if value }
  scope :with_user, lambda { |value| where('user_id = ?', value) if value }
  scope :created_since, lambda { |since| where('created_at >= ?', since) if since }
  scope :created_to, lambda { |to| where('created_at <= ?', to) if to }

end

webapp/app/controllers/upload_log_controller.rb
require 'active_support'

class UploadLogController < ApplicationController
  before_filter {authorize!(:audit, :upload_log) }

  def audit
    @users = User.order('email desc')
    @tickers = DetailUploadFile.select("distinct(ticker)").where("ticker is not null").order("ticker")
  end

  def search
    params_hash = params.except(:controller, :action, :authenticity_token, :utf8)
    user_id = params_hash['user'].to_i unless params_hash['user'].blank?
    since = params_hash['date_since'].try(:to_date).try(:beginning_of_day)
    to = params_hash['date_to'].try(:to_date).try(:end_of_day)

    ticker = params_hash['upload-log-ticker'] unless params_hash['upload-log-ticker'].blank?
    @logs = UploadLog
              .with_user(user_id)
              .with_ticker(ticker)
              .created_since(since)
              .created_to(to)
              .order('created_at desc').paginated(params)

    respond_to do |format|
      format.js { render 'display_search'}
    end
  end

  def upload_log_file
    @logs = UploadLog.find_all_by_id(params["logs_ids"].split(","))
    respond_to do |format|
      format.xls { render 'upload_log_file'}
    end
  end
end

webapp/app/views/upload_log/_logs_container.html.erb
<% unless logs.blank? %>
  <div class="large-4 large-offset-5 columns">
    <%= form_tag(export_upload_log_path(format: "xls"), method: 'get') do %>
      <%= hidden_field_tag 'logs_ids', logs.map(&:id).join(",") %>
      <button type="submit" class="button postfix success" name="export">Export</button>
    <% end %>  
  </div>
<% end %>

<% logs.each do |log| %>
  <div class="log-item">
    <%= content_tag :div, log.user.email, class: "user" %>
    <%= content_tag :div, to_PST(log.created_at), class: "date" %>
    <%= content_tag :div, log.upload_type, class: "file-type" %>
    <%= render 'layouts/upload_results', results: log.detail_upload_files %>
  </div>
<% end %>
<%= paginate @logs %>

webapp/app/views/upload_log/audit.html.erb
<% content_for :head do %>
  <script src="/assets/select2.min.js" type="text/javascript" ></script>
  <link rel="stylesheet" href="/assets/select2.custom.css">
  <%= javascript_include_tag "upload_log" %>
<% end %>

<div class="row">
  <div class="large-12 columns">
    <h1>Upload Log</h1>
    <hr>
  </div>

  <div class="large-3 columns" id="forms-container">
    <%= form_tag(export_companies_inventory_path(format: "xls")) do %>
      <%= submit_tag 'Companies Inventory', class: 'button postfix success margin-top-1em' %>
    <% end %>
    <%= form_tag(export_peers_inventory_path(format: "xls")) do %>
      <%= submit_tag 'Peers Inventory', class: 'button postfix success margin-top-1em' %>
    <% end %>
    <hr>
    <%= form_tag(search_upload_log_path, method: 'get', remote: true, class: "main-form custom") do %>
        <%= label_tag :user %>
        <%= select_tag :user, options_from_collection_for_select(@users, "id", "email"), {include_blank: true} %>

        <%= label_tag "Ticker" %>
        <%= select_tag "upload-log-ticker", options_from_collection_for_select(@tickers, "ticker", "ticker"), {include_blank: true, 'data-customforms' => "disabled"} %>
        <%= label_tag "Created date" %> <%= text_field_tag(:date_since) %>
        to <%= text_field_tag(:date_to) %>
        <button id="search-button" type="submit" class="button success" name="display_search">Search</button>
    <% end %>
  </div>

  

  <div id="log-container" class="large-9 columns log-container">
    <!-- ajax -->
  </div>

</div>

webapp/app/views/upload_log/display_search.js.erb
$("#log-container").html(
  "<%= escape_javascript(render 'upload_log/logs_container', logs: @logs)%>"
);

$(".pagination a").click(function (elem) {
	$.get($(this).attr("href"));
  return false;
});

webapp/app/views/upload_log/upload_log_file.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">

  <Styles>
    <ss:Style ss:ID="1">
      <ss:Font ss:Bold="1"/>
      <ss:Alignment ss:Horizontal="Center"/>   
    </ss:Style>
    <ss:Style ss:ID="2">
      <ss:Alignment ss:Horizontal="Center"/>   
    </ss:Style>
    <ss:Style ss:ID="3">
      <ss:Font ss:Color="red"/>
    </ss:Style>
  </Styles>
  <Worksheet ss:Name="File upload logs">
    <Table>
      <Column ss:Width="250"/>
      <Column ss:Width="150"/>
      <Column ss:Width="100"/>
      <Column ss:Width="300"/>
      <Column ss:Width="100"/>
      <Column ss:Width="700"/>
      <Row ss:StyleID="1">
        <Cell><Data ss:Type="String">User</Data></Cell>
        <Cell><Data ss:Type="String">Date</Data></Cell>      
        <Cell><Data ss:Type="String">File Type</Data></Cell>        
        <Cell><Data ss:Type="String">File Name</Data></Cell>                
        <Cell><Data ss:Type="String">Ticker</Data></Cell>
        <Cell><Data ss:Type="String">Messages</Data></Cell>
      </Row>
    <% @logs.each do |log| %>
      <% log.detail_upload_files.each do |detail| %>
        <% JSON.parse(detail["messages"]).each do |message| %>
          <Row>
            <Cell><Data ss:Type="String"><%= log.user.email %></Data></Cell>
            <Cell><Data ss:Type="String"><%= log.created_at %></Data></Cell>
            <Cell><Data ss:Type="String"><%= log.upload_type %></Data></Cell>          
            <Cell>
              <Data ss:Type="String"><% unless detail.blank? %><%= detail.file_name %><% end %></Data>
            </Cell>
            <Cell>
              <Data ss:Type="String"><% unless detail.blank? %><%= detail.ticker %><% end %></Data>
            </Cell>
            <Cell>
              <Data ss:Type="String"><% unless detail.blank? %><%= message %><% end %></Data>
            </Cell>
          </Row>
        <% end %>
      <% end %>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>