webapp/config/routes.rb
WindosorFrontend::Application.routes.draw do

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  devise_for :users

  resources :users, except: [:show, :new] do
    collection do
      get 'edit_account'
      put 'update_account'
    end
  end

  resources :groups, except: [:new] do
    collection do
      get :tickers
    end
  end

  resources :companies do
    collection do
      get   :delete_info
      get   :delete_db
      post  :destroy_top5
      post  :destroy_bod
      post  :destroy_db
      post  :destroy_peers
    end
  end

  # Search
  get "search/quick_search",  as: :quick_search
  get "search/filter_recent_search", as: :filter_recent_search
  get "search/full_search",   as: :full_search
  get "search/recent_search/:id", to: "search#recent_search", as: :top_5_recent_search
  get "search/search_log/:id", to: "search#search_log", as: :search_log


  post "search/results",      as: :search_result
  post "search/download",     as: :file_download
  post "search/group_search", as: :group_search

  # Files Upload
  get   "files/upload",       as: :file_upload
  post  "files/send_file",    as: :send_file

  # Company Peers
  get 'company_peers', to: 'company_peers#company_peers'
  get 'incoming_peers',        to: 'company_peers#incoming_peers'
  get 'peers_peers',        to: 'company_peers#peers_peers'
  post 'company_peers/incoming_peers_result', as: :incoming_peers_result
  post 'company_peers/peers_peers_single_ticker_result', as: :peers_peers_single_ticker_result
  post 'company_peers/peers_peers_ticker_list_result', as: :peers_peers_ticker_list_result

  # Export Files
  post 'companies/peers_inventory_file',     as: :export_peers_inventory
  post 'companies/companies_inventory_file', as: :export_companies_inventory

  post 'company_peers/peers_peers_single_ticker_file', as: :export_peers_peers_single_ticker
  post 'company_peers/peers_peers_ticker_list_file', as: :export_peers_peers_ticker_list
  post 'company_peers/peers_peers_raw_data_file', as: :export_peers_peers_raw_data
  post 'company_peers/peers_peers_raw_data_file_from_primary', as: :export_peers_peers_raw_data_from_primary

  post 'company_peers/incoming_peers_raw_data_file', as: :export_incoming_peers_raw_data

  # Upload Log
  get "upload_log/audit", as: :audit_log
  get "upload_log/search", as: :search_upload_log
  get "upload_log/upload_log_file", as: :export_upload_log

end

webapp/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) && !msg.empty? %>
    <div class="alert-message alert-<%= name == :notice ? "success" : "error" %>">
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <a class="close">&#215;</a>
    </div>
  <% end %>
<% end %>

webapp/app/views/layouts/_model_errors.html.erb
<div id="error_explanation" class="form-error cf">
  <h2 class="left"><%= pluralize(errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul class="left">
  <% errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>

webapp/app/views/layouts/_navigation.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1>
        <% if user_signed_in? %>
          <%= link_to "Home", user_root_path(current_user), class: 'brand' %>
        <% end %>
      </h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li class="divider"></li>
      <% if user_signed_in? %>
        <li class="<%= request.fullpath == users_path ? 'active' : '' %>">
          <%= link_to('users', users_path, class: 'nav-link') if can? :manage, User %>
        </li>
        <li class="divider"></li>
        <li class="<%= request.fullpath == full_search_path ? 'active' : '' %>">
          <%= link_to('search', full_search_path, class: 'nav-link') if can? :perform, :full_search %>
        </li>
        <li class="divider"></li>
        <li class="<%= request.fullpath == groups_path ? 'active' : '' %>">        
          <%= link_to('peers', groups_path, class: 'nav-link') if can? :create, Group %>
        </li>
        <li class="divider"></li>
        <li class="<%= request.fullpath == companies_path ? 'active' : '' %>">
          <%= link_to('companies', companies_path, class: 'nav-link') if can? :manage, Company %>
        </li>
        <li class="divider"></li>
        <li class="<%= request.fullpath == file_upload_path ? 'active' : '' %>">   
          <%= link_to('file upload', file_upload_path, class: 'nav-link') if can? :upload, :file %>
        </li>
        <li class="divider"></li>
        <li class="<%= request.fullpath == audit_log_path ? 'active' : '' %>">        
          <%= link_to('upload log', audit_log_path, class: 'nav-link') if can? :audit, :upload_log %>
        </li>
        <li class="divider"></li>
        <li class="<%= request.fullpath == incoming_peers_path ? 'active' : '' %>">
          <%= link_to('Incoming Peers', incoming_peers_path, class: 'nav-link') %>
        </li>
        <li class="divider"></li>
        <li class="<%= request.fullpath == peers_peers_path ? 'active' : '' %>">
          <%= link_to('Peers Peers', peers_peers_path, class: 'nav-link') %>
        </li>
        <li class="divider"></li>
        <li class="<%= request.fullpath == delete_info_companies_path ? 'active' : '' %>">        
          <%= link_to('delete info', delete_info_companies_path, class: 'nav-link') if can? :perfom, :delete_info %>
        </li>
        <li class="divider"></li>
        <li class="<%= request.fullpath == delete_db_companies_path ? 'active' : '' %>">
          <%= link_to('delete db', delete_db_companies_path, class: 'nav-link') if can? :perfom, :delete_db %>
        </li>
      <% end %>
      <li class="divider"></li>
    </ul>


    <!-- Right Nav Section -->
    <ul class="right">
      <li class="divider"></li>
      <li>
        <%= link_to(current_user.email, edit_account_users_path, class: "nav-link")  %>
      </li>
      <li class="has-form">
        <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, method: 'delete', class: 'button') %>
        <% else %>
          <%= link_to('Login', new_user_session_path)  %>
        <% end %>
      </li>
    </ul>
  </section>
</nav>

webapp/app/views/layouts/_upload_results.html.erb
<% results.each do |element| %>
  <%= content_tag :div, "Filename: " + element.file_name, class: "file-name" %>
  <% if element.ticker %>
    <%= content_tag :div, "Ticker: " + element.ticker, class: "ticker-name" %>
  <% end %>
  <ul class="no-bullet">
  	<% if !JSON.parse(element['messages']).empty? %>
	    <% JSON.parse(element['messages']).each do |message| %>
				<%= content_tag :li, :class => "error" do %>
				  <%= message %>
				<% end -%>
	    <% end %>
	  <% else %>
	  	<%= content_tag :li, :class => "success" do %>
			  File successfully parsed.
			<% end -%>
	  <% end %>
  </ul>
<% end %>

webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Windsor" %></title>

    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>

  </head>

  <body>

    <%= render 'layouts/messages' %>
    <% if controller_name != 'sessions' && !current_user.nil?%>
      <%= render 'layouts/navigation' %>
    <% end %>
    <div class="main" id="main" role="main">
      <div class="row">
        <%= yield %>
      </div>
    </div> <!--! end of #main -->

  </body>
</html>