webapp/config/routes.rb
WindosorFrontend::Application.routes.draw do

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  devise_for :users

  resources :users, except: [:show, :new] do
    collection do
      get 'edit_account'
      put 'update_account'
    end
  end

  resources :groups, except: [:new] do
    collection do
      get :tickers
    end
  end

  resources :companies do
    collection do
      get   :delete_info
      get   :delete_db
      post  :destroy_top5
      post  :destroy_bod
      post  :destroy_db
      post  :destroy_peers
    end
  end

  # Search
  get "search/quick_search",  as: :quick_search
  get "search/filter_recent_search", as: :filter_recent_search
  get "search/full_search",   as: :full_search
  get "search/recent_search/:id", to: "search#recent_search", as: :top_5_recent_search
  get "search/search_log/:id", to: "search#search_log", as: :search_log


  post "search/results",      as: :search_result
  post "search/download",     as: :file_download
  post "search/group_search", as: :group_search

  # Files Upload
  get   "files/upload",       as: :file_upload
  post  "files/send_file",    as: :send_file

  # Company Peers
  get 'company_peers', to: 'company_peers#company_peers'
  get 'incoming_peers',        to: 'company_peers#incoming_peers'
  get 'peers_peers',        to: 'company_peers#peers_peers'
  post 'company_peers/incoming_peers_result', as: :incoming_peers_result
  post 'company_peers/peers_peers_single_ticker_result', as: :peers_peers_single_ticker_result
  post 'company_peers/peers_peers_ticker_list_result', as: :peers_peers_ticker_list_result

  # Export Files
  post 'companies/peers_inventory_file',     as: :export_peers_inventory
  post 'companies/companies_inventory_file', as: :export_companies_inventory

  post 'company_peers/peers_peers_single_ticker_file', as: :export_peers_peers_single_ticker
  post 'company_peers/peers_peers_ticker_list_file', as: :export_peers_peers_ticker_list
  post 'company_peers/peers_peers_raw_data_file', as: :export_peers_peers_raw_data
  post 'company_peers/peers_peers_raw_data_file_from_primary', as: :export_peers_peers_raw_data_from_primary

  post 'company_peers/incoming_peers_raw_data_file', as: :export_incoming_peers_raw_data

  # Upload Log
  get "upload_log/audit", as: :audit_log
  get "upload_log/search", as: :search_upload_log
  get "upload_log/upload_log_file", as: :export_upload_log

end

webapp/app/models/company_peer.rb
# == Schema Information
#
# Table name: company_peers
#
#  id         :integer          not null, primary key
#  ticker     :string(255)      not null
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CompanyPeer < ActiveRecord::Base
	extend JSONLoadable
  attr_accessible :name, :ticker
  validates_uniqueness_of :ticker

  scope :containing_chars, lambda { |s| where("ticker ilike ?", "#{s}%") }
end

webapp/app/controllers/company_peers_controller.rb
class CompanyPeersController < ApplicationController
  def incoming_peers
  end

  def peers_peers    
  end

  def incoming_peers_result
    ticker = params[:company_peer_ticker]
    @company_peer = CompanyPeer.find_by_ticker(ticker)

    path = Rails.application.config.backend_host + Rails.application.config.post_incoming_peers_path
    @json_query = { ticker: ticker }.to_json

    find_peers(path, @json_query)
    peers = @companies_peers.map{ |x| "#{x["companyName"]}(#{x["ticker"]})"}.join(";")
    IncomingPeersSearch.create(user: current_user, company: current_user.company, tickers: ticker, peers: peers)
  end

  def peers_peers_single_ticker_result
    ticker = params[:company_peer_ticker]
    @company_peer = CompanyPeer.find_by_ticker(ticker)
    path = Rails.application.config.backend_host + Rails.application.config.post_peers_peers_single_ticker_path
    @json_query = { ticker: ticker }.to_json
    find_peers(path, @json_query)

    check_matches

    peers = @companies_peers["primaryPeers"].map{ |x| "#{x["peerCoName"]}(#{x["peerTicker"]})"}.join(";")
    PeersPeersSearch.create(user: current_user, company: current_user.company, tickers: ticker, peers: peers)
    render "peers_peers_result"
  end

  def peers_peers_ticker_list_result
    search_tickers = params[:company_peer_tickers_manual].split(" ").map(&:upcase)
    path = Rails.application.config.backend_host + Rails.application.config.post_peers_peers_ticker_list_path    
    @json_query = { tickers: search_tickers }.to_json
    find_peers(path, @json_query)
    
    check_matches
    
    peers = @companies_peers["primaryPeers"].map{ |x| "#{x["peerCoName"]}(#{x["peerTicker"]})"}.join(";")

    PeersPeersSearch.create(user: current_user, company: current_user.company, peers: peers)
    render "peers_peers_result" 
  end

  def check_matches
    @matches = {}
    primary_tickers = @companies_peers["primaryPeers"].map{ |x| x["peerTicker"] }
    secondary_tickers = @companies_peers["normalized"].map{ |x| x["secondPeer"] }
    secondary_tickers.each{ |s|
      @matches[s] = primary_tickers.include?(s)
    }    
  end

  # GET /company_peers.json
  def company_peers
    @company_peers = CompanyPeer.containing_chars(params[:q])
    respond_to do |format|
      format.html
      format.json { render json: @company_peers.map(&:attributes) }
    end
  end

  def incoming_peers_raw_data_file
    path = Rails.application.config.backend_host + Rails.application.config.post_incoming_peers_raw_data_path
    report_request(path, params[:json_query], "raw_data.xls")
  end

  def peers_peers_single_ticker_file
    path = Rails.application.config.backend_host + Rails.application.config.post_peers_peers_single_ticker_path
    download_peers_peers_file(path)
  end

  def peers_peers_raw_data_file
    path = Rails.application.config.backend_host + Rails.application.config.post_peers_peers_raw_data_path
    report_request(path, params[:json_query], "raw_data.xls")
  end

  def peers_peers_raw_data_file_from_primary
    path = Rails.application.config.backend_host + Rails.application.config.post_peers_peers_ticker_list_raw_data_path
    report_request(path, params[:json_query], "raw_data.xls")
  end

  def peers_peers_ticker_list_file
    path = Rails.application.config.backend_host + Rails.application.config.post_peers_peers_ticker_list_path
    download_peers_peers_file(path)
  end
  
  private
  def find_peers(path, json_query)
    @companies_peers = []
    RestClient.post(path, json_query, {content_type: :json}) do |response, request|
      if response.code == 200
        @companies_peers = JSON.parse(response.body)
      else
      end
    end
  end

  def download_peers_peers_file(path)
    json_query = params[:json_query]
    
    find_peers(path, json_query)
    @primary_peers = @companies_peers["primaryPeers"]
    @companies_peers = (@companies_peers["normalized"] + @companies_peers["unnormalized"]).group_by { |p| p["secondPeer"] }
    @companies_peers = @companies_peers.sort {|a, b| [a[1][1]["weight"], a[1][0]["weight"]] <=> [b[1][1]["weight"], b[1][0]["weight"]]}
    @companies_peers.reverse!

    respond_to do |format|
      format.xls { render 'peers_peers_result'}
    end
  end
end

webapp/app/views/company_peers/incoming_peers.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "company_peers" %>
<% end %>

<h1>Search For Companies</h1>
<hr>
<div class="row">
  <%= form_tag(incoming_peers_result_path) do %>
    <div class="large-3 columns">
      <p>Target Company Ticker</p>
    </div>
    <div class="large-7 columns">
      <%= text_field_tag :company_peer_ticker, nil, class: "company-peer-ticker" %>
    </div>
    <div class="large-2 columns">
      <%= submit_tag 'Search', class: 'button postfix' %>
    </div>
  <% end %>
</div>

webapp/app/views/company_peers/incoming_peers_result.html.erb
Company Ticker: <%= @company_peer.name %> (<%= @company_peer.ticker %>)

<%= form_tag(export_incoming_peers_raw_data_path) do %>
  <%= hidden_field_tag 'json_query', @json_query %>
  <%= submit_tag 'Download Incoming File', class: 'big-button' %>
<% end %>

<div class="panel">
  <% @companies_peers.each { |peer| %>
    <p><%= peer['companyName'] %>(<%= peer['ticker'] %>)</p>
  <% } %>
<div>

webapp/app/views/company_peers/incoming_peers_result.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">

  <Styles>
    <ss:Style ss:ID="1">
      <ss:Font ss:Bold="1"/>
      <ss:Alignment ss:Horizontal="Center"/>   
    </ss:Style>
  </Styles>
  <Worksheet ss:Name="company peers">
    <Table>
      <Column ss:Width="250"/>
      <Column ss:Width="150"/>
      <Row ss:StyleID="1">
        <Cell><Data ss:Type="String">Company Name</Data></Cell>
        <Cell><Data ss:Type="String">Ticker</Data></Cell>
      </Row>
    <% @companies_peers.each do |peer| %>
      <Row>
        <Cell><Data ss:Type="String"><%= peer['companyName'] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= peer['ticker']  %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

webapp/app/views/company_peers/index.html.erb
<%= form_tag(company_peers_search_result_path) do %>

  <div class="field">
    <%= text_field_tag :company_peer_ticker %>
    <%= submit_tag 'Search', class: 'big-button' %>
  </div>

<% end %>

webapp/app/views/company_peers/peers_peers.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "company_peers" %>
<% end %>

<div id="ticker_list_form" >
  <h1>Ticker List Manual</h1>
  <hr>
  <%= form_tag(peers_peers_ticker_list_result_path) do %>
    <div class="field">
      <%= text_field_tag :company_peer_tickers_manual, nil, placeholder: "Space separated tickers" %>
      <%= submit_tag 'Search', class: 'button success' %>
    </div>
  <% end %>
</div>

<div id="single_ticker_form">
  <h1>Target Company Ticker</h1>
  <hr>
  <%= form_tag(peers_peers_single_ticker_result_path) do %>
    <div class="field">
      <%= text_field_tag :company_peer_ticker, nil, class: "company-peer-ticker" %>
      <%= submit_tag 'Search', class: 'button success margin-top-1em' %>
    </div>
  <% end %>
</div>

webapp/app/views/company_peers/peers_peers.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">

  <Styles>
    <ss:Style ss:ID="1">
      <ss:Font ss:Bold="1"/>
      <ss:Alignment ss:Horizontal="Center"/>   
    </ss:Style>
  </Styles>
  <Worksheet ss:Name="company peers">
    <Table>
      <Column ss:Width="250"/>
      <Column ss:Width="150"/>
      <Column ss:Width="80"/>
      <Column ss:Width="80"/>
      <Row ss:StyleID="1">
        <Cell><Data ss:Type="String">Company Name</Data></Cell>
        <Cell><Data ss:Type="String">Ticker</Data></Cell>
        <Cell><Data ss:Type="String">Score</Data></Cell>
        <Cell><Data ss:Type="String">Simple Count</Data></Cell>
      </Row>
    <% @companies_peers.each do |peer| %>
      <Row>
        <Cell><Data ss:Type="String"><%= peer[1][0]["secondPeerName"] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= peer[1][0]["secondPeer"]  %></Data></Cell>
        <Cell><Data ss:Type="String"><%= peer[1][0]["weight"] %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= peer[1][1]["weight"] %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

webapp/app/views/company_peers/peers_peers_result.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "company_peers" %>
<% end %>

<% if @company_peer %>
  <%= @company_peer.name %> (<%= @company_peer.ticker %>) "SECONDARY PEER"
<% end %></br></br>

<% unless @companies_peers["normalized"].blank? %>
  <% path = request.path == "/company_peers/peers_peers_ticker_list_result" ? export_peers_peers_ticker_list_path(format: "xls") : export_peers_peers_single_ticker_path(format: "xls") %>

  <%= form_tag(path) do %>
    <%= hidden_field_tag 'json_query', @json_query %>
    <%= submit_tag 'Download Report XLS', class: 'big-button' %>
  <% end %>


  <% raw_path = request.path == "/company_peers/peers_peers_single_ticker_result" ? export_peers_peers_raw_data_path : 
    export_peers_peers_raw_data_from_primary_path %>

  <%= form_tag(raw_path) do %>
    <%= hidden_field_tag 'json_query', @json_query %>
    <%= submit_tag 'Download Research Inputs', class: 'big-button' %>
  <% end %>

  <div class="row">
    <div class="large-4 columns">
      <input type="radio" name="secondary_type" value="Unnormalized" checked="checked">Peers of Peers Total
      <input type="radio" name="secondary_type" value="Normalized">Normalized Score
    </div>
    <div class="large-4 columns">
      <%= select_tag :topAmount, options_for_select((5..50).step(5).push("All results"), "All results") %>
    </div>
    <div class="large-4 columns">
      <% if @company_peer %>
        <%= @company_peer.name %> (<%= @company_peer.ticker %>) "PRIMARY PEER"
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="large-8 columns">
    
      <div id="normalized" class="hidden">
        <div class="section-container accordion" data-section="accordion">
          <% @companies_peers["normalized"].each{|secondary| %>
            <section>
              <p class="title" data-section-title>
                <%= check_box_tag nil, nil, @matches[secondary['secondPeer']], disabled: true %>
                <%= secondary["secondPeerName"] %>(<%= secondary["secondPeer"] %>)
                <span class="right"><%= secondary["weight"] %></span>
              </p>
              <div class="content" data-section-content>
                <% secondary["primaryPeersWeights"].each{|primary| %>

                  <%= primary["primaryPeerName"] %>(<%= primary["primaryPeer"] %>)<a href="<%= primary["link"] %>">LINK</a>
                  <span class="right"><%= primary["weight"] %></span></br>                     
                <% } %>
              </div>
            </section>
          <% } %>    
        </div>
      </div>

      <div id="unnormalized"  >
        <div class="section-container accordion" data-section="accordion">
          <% @companies_peers["unnormalized"].each{|secondary| %>
            <section>
              <p class="title" data-section-title>
                <%= check_box_tag nil, nil, @matches[secondary['secondPeer']], disabled: true %>
                <%= secondary["secondPeerName"] %>(<%= secondary["secondPeer"] %>)
                <span class="right"><%= secondary["weight"].to_i %></span>
              </p>
              <div class="content" data-section-content>
                <% secondary["primaryPeersWeights"].each{|primary| %>
                  <%= primary["primaryPeerName"] %>(<%= primary["primaryPeer"] %>)<a href="<%= primary["link"] %>">LINK</a>
                  <span class="right"><%= primary["weight"].to_i %></span></br>
                <% } %>
              </div>
            </section>      
          <% } %>    
        </div>
      </div>
    </div>
  <% else %>
    <h3>No results to show</h3>
  <% end %>

  <% unless @companies_peers["primaryPeers"].blank? %>
    <div class="large-4 columns">
      <div id="primary-peers" class="panel">
        <div class="row">          
          <div class="large-8 columns">
              <% @companies_peers["primaryPeers"].each{|primary| %>
              <p class="peer-name" title="<%= primary["peerCoName"] %>">
                    <%= primary["peerCoName"] %>
              </p>
              <% } %>
          </div>
          <div class="large-4 columns">
              <% @companies_peers["primaryPeers"].each{|primary| %>
              <p class="peer-ticker" title="<%= primary["peerTicker"] %>">
                <%= primary["peerTicker"] %> 
              </p>
              <% } %>
          </div>         
        </div><!-- row -->
      </div>
    </div>
  <% end %>
</div>

webapp/app/views/company_peers/peers_peers_result.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">

  <Styles>
    <ss:Style ss:ID="1">
      <ss:Font ss:Bold="1"/>
      <ss:Alignment ss:Horizontal="Center"/>   
    </ss:Style>
  </Styles>
  <Worksheet ss:Name="company peers">
    <Table>
      <Column ss:Width="250"/>
      <Column ss:Width="150"/>
      <Column ss:Width="80"/>
      <Column ss:Width="80"/>
      <Row ss:StyleID="1">
        <Cell><Data ss:Type="String">Company Name</Data></Cell>
        <Cell><Data ss:Type="String">Ticker</Data></Cell>
        <Cell><Data ss:Type="String">Peer Peer Totals</Data></Cell>
        <Cell><Data ss:Type="String">Normalized</Data></Cell>
      </Row>
      <% @companies_peers.each do |peer| %>
      <Row>
        <Cell><Data ss:Type="String"><%= peer[1][0]["secondPeerName"] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= peer[1][0]["secondPeer"]  %></Data></Cell>
        <Cell><Data ss:Type="String"><%= peer[1][1]["weight"] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= peer[1][0]["weight"] %></Data></Cell>
      </Row>
      <% end %>
    </Table>
  </Worksheet>

  <Worksheet ss:Name="primary peers">
    <Table>
      <Column ss:Width="250"/>
      <Column ss:Width="150"/>
      <Row ss:StyleID="1">
        <Cell><Data ss:Type="String">Company Name</Data></Cell>
        <Cell><Data ss:Type="String">Ticker</Data></Cell>
      </Row>
      <% @primary_peers.each do |peer| %>
      <Row>
        <Cell><Data ss:Type="String"><%= peer["peerCoName"] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= peer["peerTicker"]  %></Data></Cell>
      </Row>
      <% end %>
    </Table>    
  </Worksheet>
</Workbook>

webapp/app/views/company_peers/search_result.html.erb
Company Peer: <%= @company_peer.name %> (<%= @company_peer.ticker %>)

<% @companies_peers.each { |peer| %>
  <p><%= peer['companyName'] %>(<%= peer['ticker'] %>)</p> 
<% } %>