webapp/config/routes.rb
WindosorFrontend::Application.routes.draw do

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  devise_for :users

  resources :users, except: [:show, :new] do
    collection do
      get 'edit_account'
      put 'update_account'
    end
  end

  resources :groups, except: [:new] do
    collection do
      get :tickers
    end
  end

  resources :companies do
    collection do
      get   :delete_info
      get   :delete_db
      post  :destroy_top5
      post  :destroy_bod
      post  :destroy_db
      post  :destroy_peers
    end
  end

  # Search
  get "search/quick_search",  as: :quick_search
  get "search/filter_recent_search", as: :filter_recent_search
  get "search/full_search",   as: :full_search
  get "search/recent_search/:id", to: "search#recent_search", as: :top_5_recent_search
  get "search/search_log/:id", to: "search#search_log", as: :search_log


  post "search/results",      as: :search_result
  post "search/download",     as: :file_download
  post "search/group_search", as: :group_search

  # Files Upload
  get   "files/upload",       as: :file_upload
  post  "files/send_file",    as: :send_file

  # Company Peers
  get 'company_peers', to: 'company_peers#company_peers'
  get 'incoming_peers',        to: 'company_peers#incoming_peers'
  get 'peers_peers',        to: 'company_peers#peers_peers'
  post 'company_peers/incoming_peers_result', as: :incoming_peers_result
  post 'company_peers/peers_peers_single_ticker_result', as: :peers_peers_single_ticker_result
  post 'company_peers/peers_peers_ticker_list_result', as: :peers_peers_ticker_list_result

  # Export Files
  post 'companies/peers_inventory_file',     as: :export_peers_inventory
  post 'companies/companies_inventory_file', as: :export_companies_inventory

  post 'company_peers/peers_peers_single_ticker_file', as: :export_peers_peers_single_ticker
  post 'company_peers/peers_peers_ticker_list_file', as: :export_peers_peers_ticker_list
  post 'company_peers/peers_peers_raw_data_file', as: :export_peers_peers_raw_data
  post 'company_peers/peers_peers_raw_data_file_from_primary', as: :export_peers_peers_raw_data_from_primary

  post 'company_peers/incoming_peers_raw_data_file', as: :export_incoming_peers_raw_data

  # Upload Log
  get "upload_log/audit", as: :audit_log
  get "upload_log/search", as: :search_upload_log
  get "upload_log/upload_log_file", as: :export_upload_log

end

webapp/app/models/search.rb
# == Schema Information
#
# Table name: searches
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  json_query  :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  company_id  :integer
#  report_type :string(255)
#  peers       :text
#  tickers     :text
#  type        :string(255)
#  group_name  :string(255)
#

class Search < ActiveRecord::Base
  attr_accessible :user, :company, :report_type
  belongs_to :user
  belongs_to :company

  validates :user_id, presence: true

  scope :by_company, lambda { |company, n|
    where(company_id: company.id).order("created_at desc").limit(n)
  }
  scope :last_ordered_by_date, lambda { |n|
    order("created_at desc").limit(n)
  }
end

webapp/app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_filter :get_form_values, only: [:full_search, :recent_search]

  def quick_search
    authorize!(:perform, :quick_search)
    @groups = current_user.is_client? ? Group.by_company(current_user.company) : @groups = Group.all
    @users = User.order('email desc')
  end

  def filter_recent_search
    authorize!(:perform, :recent_search)
    user_id =  params["user"].to_i unless params["user"].blank?
    n = params["results"].blank? ? 20 : params["results"].to_i
    if current_user.is_super?
      if user_id
        @searches = Search.last_ordered_by_date(n).where(user_id: user_id)
      else
        @searches = Search.last_ordered_by_date(n)
      end
    elsif current_user.is_client?
      @searches = Search.by_company(current_user.company, n)
    end
  end
  
  def full_search
    authorize!(:perform, :full_search)
    @start_year = 2010
    @end_year = Time.now.year-1
  end

  def results
    params_hash = params.except(:controller, :action, :authenticity_token, :utf8, :role_form)
    Top5Search.create(user: current_user, json_query: params_hash.to_json, company: current_user.company)
    json_query = QueryGenerator.json_query(params_hash)
    path = Rails.application.config.backend_host + Rails.application.config.post_query_path
    headers ={content_type: :json}

    @tickers = []
    RestClient::Request.execute(:method => :post, :url => path, :payload => json_query, :headers => headers, :timeout => -1)  do |response, _|
      @tickers = JSON.parse(response)
    end
  end

  def download
    json_query = { range: params[:range].to_i, companies: params[:companies]}.to_json
    perform_search(json_query, Constants::TOP5_REPORT)
  end

  def group_search
    group = Group.find(params[:group])
    tickers = group.tickers.map { |company| company[:name] + " (" + company[:ticker] + ")" }
    CompanyPeerSearch.create(user: current_user, company: current_user.company, tickers: tickers.join(";"), group_name: group.name, report_type: params[:report])
    json_query = { range: 3, companies: group.tickers.map(&:cusip) }.to_json
    perform_search(json_query, params[:report])
  end

  def recent_search
    authorize!(:perform, :recent_search)    
    @params_hash = JSON.parse(Top5Search.find(params[:id]).json_query)

    render "top_5_recent_search_log"
  end

  def search_log
    @search = Search.find(params[:id])
  end

  private
  def get_form_values
    @primary_roles = PrimaryRole.order("name asc")
    @eq_comp_values = EquityCompensation.order("value asc")
    @cash_comp_values = CashCompensation.order("value asc")    
  end

  def perform_search(json_query, report_type)
    case report_type
      when Constants::TOP5_REPORT
        path = Rails.application.config.backend_host + Rails.application.config.post_download_top5_report_path
      when Constants::BOD_REPORT
        path = Rails.application.config.backend_host + Rails.application.config.post_download_bod_report_path
      when Constants::FULL_REPORT
        path = Rails.application.config.backend_host + Rails.application.config.post_download_full_report_path
    end

    report_request(path, json_query, "report.xls")
  end
end

webapp/app/helpers/search_helper.rb
module SearchHelper
  def log_search_path(search)
    case search.type
    when Top5Search.name
      top_5_recent_search_path(search)
    else
      search_log_path(search)
    end
  end
end

webapp/app/views/search/_quick_launch.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Quick Launch</h1>
    <hr>
  </div>

  <% if can? :perform, :recent_search %>
    <div class="large-3 columns">
      <!-- activity log -->
      <div class="recent-search-container">
        <h2 class="title">Recent Searches</h2>
        <div id="forms-container">
          <%= form_tag(filter_recent_search_path, method: 'get', remote: true, class: "main-form custom") do %>
            <% unless current_user.is_client? %>
              <%= label_tag "User" %> <%= select_tag :user, options_from_collection_for_select(@users, "id", "email"), {include_blank: true} %>
            <% end %> <%# Client users cannot search by user. The results are his company's searches %>
              <%= label_tag "Results" %> <%= select_tag :results, options_for_select([5, 15, 25, 50]), {include_blank: true} %>
              <button type="submit" class="button postfix success" name="display_search">Search</button>
          <% end %>
        </div>
        <div id="recent-search-results">
                  
        </div>
      </div>
    </div>
  <% end %>

  <div class="large-<%= (can? :perform, :recent_search) ? 9 : 12 %> columns">
    <!-- quick launch -->
    <%= form_tag(group_search_path, class: "custom") do %>
      <div class="row">
        <div class="large-3 columns">
          <label for="right-label" class="text-uppercase inline">Select peer group</label>
        </div>
        <div class="large-9 columns">
          <%= select_tag :group, options_from_collection_for_select(groups, "id", "name") %>
        </div>
        <div class="large-3 columns">
          <label for="right-label" class="text-uppercase inline">Select report</label>
        </div>
        <div class="large-9 columns">
          <%= select_tag :report, options_for_select(Constants::REPORT_TYPES) %>
        </div>
        <div class="large-12 columns">
          <%= submit_tag "Select", class: 'button' %>
          <%= link_to('Create new peer group', groups_path) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

webapp/app/views/search/_quick_search.html.erb
<div class="span9">
  <!-- quick launch -->
  <div class="side-container quick-launch">
    <h2 class="title">Quick Launch</h2>
    <div class="content">
      <%= form_tag('/groups') do %>
        <label class="label">Select peer group
          <%= select_tag :group, options_from_collection_for_select(Group.all, "id", "name") %>
        </label>
        <label class="label">Select report
          <%= select_tag :report, options_for_select(Constants::REPORTS) %>
        </label>
        <%= submit_tag "Select" %>
        <%= link_to('Create new peer group', new_group_path, class: 'right') %>
      <% end %>
    </div>
  </div>
</div>
<div class="span3">
  <!-- activity log -->
  <div class="side-container activity-log">
    <h2 class="title">Activity Log</h2>
    <div class="content">
      <ul class="documents-list">
        <li class="document"><a href="#">Document 01</a></li>
        <li class="document"><a href="#">Document 02</a></li>
        <li class="document"><a href="#">Document 03</a></li>
        <li class="document"><a href="#">Document 04</a></li>
      </ul>
    </div>
  </div>
</div>

webapp/app/views/search/_recent_search_results.html.erb
<% if searches.blank? %>
  No results to show
<% else %>
  <% searches.each{ |s| %>
    <div class="recent-search-item">
      <p class="username"><%= s.user.email %></p>
      <p class="report"><%= to_PST(s.created_at) %></p>
      <p class="report"><%= s.report_type %></p>
      <a href="<%= log_search_path(s) %>" class="small button">View</a>
    </div>
  <% } %>
<% end %>

webapp/app/views/search/filter_recent_search.js.erb
$("#recent-search-results").html(
  "<%= escape_javascript(render 'search/recent_search_results', searches: @searches)%>"
);

webapp/app/views/search/full_search.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "search" %>
<% end %>

<h1 class="title">Executive compensation</h1>
<hr>
<div class="span9">
  <%= form_tag(search_result_path, class: "main-form custom" ) do %>
    <div class="row">
      <div class="large-6 columns">
        <label>Filter by Year</label>
        <%= select_tag '[year]', options_for_select((@start_year..@end_year).to_a.reverse) %>
      </div>
    </div>
    <div class="form-container relative" id="forms-container">
      <div class="basic-group hidden">
        <hr>
        <div class="role-selector row">
          <div class="large-6 columns">
            <label>Role</label>
            <%= select_tag '[role_form][role]', options_from_collection_for_select(@primary_roles, "name", "name"), {include_blank: true} %>
          </div>
          <div class="large-6 columns">
            <label>Pay rank</label>
            <%= select_tag '[role_form][pay_rank]', options_for_select((1..5)), {include_blank: true} %>
          </div>
        </div>
        <div class="filters">

          <!-- cash compensation -->
          <div class="row">
            <div class="large-12 columns">
              <label>cash compensation</label>
            </div>
            <div class="large-4 columns combo_div">
              <%= select_tag '[role_form][cash_comp][type]', options_from_collection_for_select(@cash_comp_values, "field", "value"), {include_blank: true} %>
            </div>
            <div class="large-4 columns">
              <input type="text" placeholder="Greater than ($)" name='[role_form][cash_comp][gt]' disabled="disabled">
            </div>
            <div class="large-4 columns">
              <input type="text" placeholder="Less than ($)" name='[role_form][cash_comp][lt]' disabled="disabled">
            </div>
          </div>

          <!-- equity compensation -->
          <div class="row">
            <div class="large-12 columns">
              <label>equity compensation</label>
            </div>
            <div class="large-4 columns combo_div">
              <%= select_tag '[role_form][eq_comp][type]', options_from_collection_for_select(@eq_comp_values, "field", "value"), {include_blank: true} %>
            </div>
            <div class="large-4 columns">
              <input type="text" placeholder="Greater than ($)" name='[role_form][eq_comp][gt]' disabled="disabled">
            </div>
            <div class="large-4 columns">
              <input type="text" placeholder="Less than ($)" name='[role_form][eq_comp][lt]' disabled="disabled">
            </div>
          </div>

          <hr>

          <!-- other criteria -->
          <!-- Founder -->
          <div class="row padding-bottom-10">
            <div class="large-3 columns">
              <span>Founder</span>
            </div>
            <div class="large-9 columns radio-button">
              <label for="radio1">
                <%= radio_button_tag '[role_form][founder]', 'X' %>
                <span class="custom radio"></span> YES
              </label>
              <label for="radio1">
                <%= radio_button_tag '[role_form][founder]', '_' %>
                <span class="custom radio"></span> NO
              </label>
              <label for="radio1">
                <%= radio_button_tag '[role_form][founder]', 'N/A' %>
                <span class="custom radio"></span> N/A
              </label>
            </div>
          </div>

          <!-- transition period -->
          <div class="row">
            <div class="large-3 columns">
              <span>Transition period</span>
            </div>
            <div class="large-9 columns radio-button">
              <label for="radio1">
                <%= radio_button_tag '[role_form][trans_period]', 'Yes' %>
                <span class="custom radio"></span> YES
              </label>
              <label for="radio1">
                <%= radio_button_tag '[role_form][trans_period]', 'No' %>
                <span class="custom radio"></span> NO
              </label>
              <label for="radio1">
                <%= radio_button_tag '[role_form][trans_period]', 'N/A' %>
                <span class="custom radio"></span> N/A
              </label>
            </div>  
          </div>


          </div>

        </div>

      </div>
    </div>

    <div class="hidden">
      <label for="radio1"><input name="radio1" type="radio" id="radio1" disabled style="display:none;"><span class="custom radio"></span> Radio Button 3</label>
    </div>

    <div class="form-actions">
      <button type="submit" class="btn">Search</button>
      <!-- add another role button -->
      <a class="button secondary cto absolute" href="#" id="js-new-form">Add another role</a>
    </div>
  <% end %>
</div>

webapp/app/views/search/quick_search.html.erb
<%= render 'search/quick_launch', groups: @groups %>

webapp/app/views/search/recent_search.html.erb
<div class="span9">
  <h1>Executive compensation</h1>
  <hr>
  <%= form_tag(search_result_path, class: "main-form " ) do %>
    <div class="form-container relative" id="forms-container">      
      
    <% @params_hash.each_with_index { |(k, value), i|%>
    <% if k.starts_with? 'role_form' %>
        <div class="basic-group">
          <div class="role-selector row">

            <div class="large-6 columns">
              <label>Role</label>
              <%= select_tag "[role_form_#{i + 1}[role]",
                options_from_collection_for_select(@primary_roles, "name", "name", @params_hash[k].try(:[], "role")), {include_blank: true} %>
            </div>
            
            <div class="large-6 columns">
              <label>Pay rank</label>
              <%= select_tag "[role_form_#{i + 1}][pay_rank]", options_for_select((1..5), @params_hash[k].try(:[], "pay_rank")), {include_blank: true} %>
            </div>
          </div>

          <div class="filters">
            <!-- cash compensation -->
            <div class="row">
              <div class="large-12 columns">
                <label>cash compensation</label>
              </div>
              <div class="large-4 columns">
              <%= select_tag "[role_form_#{i + 1}][cash_comp][type]",
                options_from_collection_for_select(@cash_comp_values, "field", "value",
                @params_hash[k].try(:[], "cash_comp").try(:[], "type")), {include_blank: true} %>
              </div>
              <div  class="large-4 columns">
              <%= text_field_tag "[role_form_#{i + 1}][cash_comp][gt]", @params_hash[k].try(:[], "cash_comp").try(:[], "gt"), placeholder: "Greater than ($)" %>
              </div>
              <div class="large-4 columns">
              <%= text_field_tag "[role_form_#{i + 1}][cash_comp][lt]", @params_hash[k].try(:[], "cash_comp").try(:[], "lt"), placeholder: "Less than ($)" %>
              </div>
            </div>

            <!-- equity compensation -->
            <div class="row">
              <div class="large-12 columns">
                <label>equity compensation</label>
              </div>
              <div class="large-4 columns">
                <%= select_tag "[role_form_#{i + 1}][eq_comp][type]",
                options_from_collection_for_select(@eq_comp_values, "field", "value",
                @params_hash[k].try(:[], "eq_comp").try(:[], "type")), {include_blank: true} %>
              </div>
              <div class="large-4 columns">
                <%= text_field_tag "[role_form_#{i + 1}][eq_comp][gt]", @params_hash[k].try(:[], "eq_comp").try(:[], "gt"), placeholder: "Greater than ($)" %>
              </div>
              <div class="large-4 columns">
                <%= text_field_tag "[role_form_#{i + 1}][eq_comp][lt]", @params_hash[k].try(:[], "eq_comp").try(:[], "lt"), placeholder: "Less than ($)" %>
              </div>
            </div>
          
          <!-- CEO tenure -->
          <div class="row">
            <div class="large-12 columns">
              <label>CEO tenure</label>
            </div>
            <div class="large-6 columns">
              <%= text_field_tag "[role_form_#{i + 1}][ceo_tenure][gt]", @params_hash[k].try(:[], "ceo_tenure").try(:[], "gt"), placeholder: "Greater than (yrs)" %>
            </div>
            <div class="large-6 columns">
              <%= text_field_tag "[role_form_#{i + 1}][ceo_tenure][lt]", @params_hash[k].try(:[], "ceo_tenure").try(:[], "gt"), placeholder: "Less than (yrs)" %>
            </div>
          </div>

          <hr>
          
          <!-- other criteria -->
          <div class="row padding-bottom-10">
            <!-- Founder -->
            <div class="large-3 columns">
              <span>Founder</span>
            </div>
            <div class="large-9 columns radio-button">
              <%= label_tag 'Yes' %> <%= radio_button_tag "[role_form_#{i + 1}][founder]", 'Yes', @params_hash[k].try(:[], "founder") == "Yes" %>
              <%= label_tag 'No' %> <%= radio_button_tag "[role_form_#{i + 1}][founder]", 'No', @params_hash[k].try(:[], "founder") == "No" %>
              <%= label_tag 'N/A' %> <%= radio_button_tag "[role_form_#{i + 1}][founder]", 'N/A', @params_hash[k].try(:[], "founder") == "N/A" %>
            </div>

            <!-- transition period -->
              <div class="large-3 columns">
                <span>Transition period</span>
              </div>
              <div class="large-9 columns radio-button">
                <%= label_tag 'Yes' %> <%= radio_button_tag "[role_form_#{i + 1}][trans_period]", 'Yes', @params_hash[k].try(:[], "trans_period") == "Yes" %>
              
                <%= label_tag 'No' %> <%= radio_button_tag "[role_form_#{i + 1}][trans_period]", 'No', @params_hash[k].try(:[], "trans_period") == "No" %>
                <%= label_tag 'N/A' %> <%= radio_button_tag "[role_form_#{i + 1}][trans_period]", 'N/A', @params_hash[k].try(:[], "trans_period") == "N/A" %>
              </div>
            
          </div>
        </div>
      </div>
    <% end %>
    <% } %>

    <div class="hidden">
      <label for="radio1"><input name="radio1" type="radio" id="radio1" disabled style="display:none;"><span class="custom radio"></span> Radio Button 3</label>
    </div>

    <div class="form-actions">
      <button type="submit" class="btn">Search</button>
    </div>

  <% end %>
</div>

webapp/app/views/search/results.html.erb
<h1 class="main-title">Search results</h1>
<% if @tickers.blank? %>
  No search results.
<% else %>
  <%= form_tag(file_download_path, class: "main-form" ) do %>
    Years before: <%= select_tag 'range', options_for_select((1..3), 1) %>
    </br>
    <% @tickers.each{ |k| %>
      <% if k.is_a? Hash %>
        <%= check_box_tag 'companies[]', k["cusip"] %> <%= k["name"] %>
        </br>
      <% end %>
    <% } %>
    <button type="submit" class="btn right">Download File</button>
  <% end %>
<% end %>

webapp/app/views/search/search_log.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1><%= @search.report_type %></h1>
    <hr>
    <div class="search-info-container">
      <h4 class="title">SEARCH INFO</h4>
      <p class="info"> Requested by <b><%= @search.user.email %></b> 
      <%= "from " + @search.company.name if @search.company %>
      on <b><%= @search.created_at.strftime("%Y-%m-%d at %H:%M") %></b>
      </p>
    </div>
  </div>
  <% if @search.group_name %>
    <div class="large-3 columns">
      <div class="recent-search-container">
        <h2 class="title">Group</h2>
        <p><%= @search.group_name %></p>
      </div>
    </div>
  <% end %>
  <div class="large-3 columns">
      <div class="recent-search-container">
        <h2 class="title">Tickers</h2>
        <% unless @search.tickers.blank? %>
          <% @search.tickers.split(";").each do |s| %>
            <p><%= s %></p>
          <% end %>
        <% end %>
      </div>
  </div>
  <% if @search.peers %>
    <div class="large-9 columns">
      <h3>Peers</h3>
      <ul class="square list-inside">
        <% @search.peers.split(";").each do |s| %>
          <li><%= s %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="large-12 columns">
    <hr>
    <%= link_to "Back", quick_search_path %>
  </div>
</div>

webapp/app/views/search/top_5_recent_search_log.html.erb
<div class="span9">
  <h1>Executive compensation</h1>
  <hr>
  <%= form_tag(search_result_path, class: "main-form " ) do %>
    <div class="form-container relative" id="forms-container">      
      
    <% @params_hash.each_with_index { |(k, value), i|%>
    <% if k.starts_with? 'role_form' %>
        <div class="basic-group">
          <div class="role-selector row">

            <div class="large-6 columns">
              <label>Role</label>
              <%= select_tag "[role_form_#{i + 1}[role]",
                options_from_collection_for_select(@primary_roles, "name", "name", @params_hash[k].try(:[], "role")), {include_blank: true} %>
            </div>
            
            <div class="large-6 columns">
              <label>Pay rank</label>
              <%= select_tag "[role_form_#{i + 1}][pay_rank]", options_for_select((1..5), @params_hash[k].try(:[], "pay_rank")), {include_blank: true} %>
            </div>
          </div>

          <div class="filters">
            <!-- cash compensation -->
            <div class="row">
              <div class="large-12 columns">
                <label>cash compensation</label>
              </div>
              <div class="large-4 columns">
              <%= select_tag "[role_form_#{i + 1}][cash_comp][type]",
                options_from_collection_for_select(@cash_comp_values, "field", "value",
                @params_hash[k].try(:[], "cash_comp").try(:[], "type")), {include_blank: true} %>
              </div>
              <div  class="large-4 columns">
              <%= text_field_tag "[role_form_#{i + 1}][cash_comp][gt]", @params_hash[k].try(:[], "cash_comp").try(:[], "gt"), placeholder: "Greater than ($)" %>
              </div>
              <div class="large-4 columns">
              <%= text_field_tag "[role_form_#{i + 1}][cash_comp][lt]", @params_hash[k].try(:[], "cash_comp").try(:[], "lt"), placeholder: "Less than ($)" %>
              </div>
            </div>

            <!-- equity compensation -->
            <div class="row">
              <div class="large-12 columns">
                <label>equity compensation</label>
              </div>
              <div class="large-4 columns">
                <%= select_tag "[role_form_#{i + 1}][eq_comp][type]",
                options_from_collection_for_select(@eq_comp_values, "field", "value",
                @params_hash[k].try(:[], "eq_comp").try(:[], "type")), {include_blank: true} %>
              </div>
              <div class="large-4 columns">
                <%= text_field_tag "[role_form_#{i + 1}][eq_comp][gt]", @params_hash[k].try(:[], "eq_comp").try(:[], "gt"), placeholder: "Greater than ($)" %>
              </div>
              <div class="large-4 columns">
                <%= text_field_tag "[role_form_#{i + 1}][eq_comp][lt]", @params_hash[k].try(:[], "eq_comp").try(:[], "lt"), placeholder: "Less than ($)" %>
              </div>
            </div>
          
          <!-- CEO tenure -->
          <div class="row">
            <div class="large-12 columns">
              <label>CEO tenure</label>
            </div>
            <div class="large-6 columns">
              <%= text_field_tag "[role_form_#{i + 1}][ceo_tenure][gt]", @params_hash[k].try(:[], "ceo_tenure").try(:[], "gt"), placeholder: "Greater than (yrs)" %>
            </div>
            <div class="large-6 columns">
              <%= text_field_tag "[role_form_#{i + 1}][ceo_tenure][lt]", @params_hash[k].try(:[], "ceo_tenure").try(:[], "gt"), placeholder: "Less than (yrs)" %>
            </div>
          </div>

          <hr>
          
          <!-- other criteria -->
          <div class="row padding-bottom-10">
            <!-- Founder -->
            <div class="large-3 columns">
              <span>Founder</span>
            </div>
            <div class="large-9 columns radio-button">
              <%= label_tag 'Yes' %> <%= radio_button_tag "[role_form_#{i + 1}][founder]", 'Yes', @params_hash[k].try(:[], "founder") == "Yes" %>
              <%= label_tag 'No' %> <%= radio_button_tag "[role_form_#{i + 1}][founder]", 'No', @params_hash[k].try(:[], "founder") == "No" %>
              <%= label_tag 'N/A' %> <%= radio_button_tag "[role_form_#{i + 1}][founder]", 'N/A', @params_hash[k].try(:[], "founder") == "N/A" %>
            </div>

            <!-- transition period -->
              <div class="large-3 columns">
                <span>Transition period</span>
              </div>
              <div class="large-9 columns radio-button">
                <%= label_tag 'Yes' %> <%= radio_button_tag "[role_form_#{i + 1}][trans_period]", 'Yes', @params_hash[k].try(:[], "trans_period") == "Yes" %>
              
                <%= label_tag 'No' %> <%= radio_button_tag "[role_form_#{i + 1}][trans_period]", 'No', @params_hash[k].try(:[], "trans_period") == "No" %>
                <%= label_tag 'N/A' %> <%= radio_button_tag "[role_form_#{i + 1}][trans_period]", 'N/A', @params_hash[k].try(:[], "trans_period") == "N/A" %>
              </div>
            
          </div>
        </div>
      </div>
    <% end %>
    <% } %>

    <div class="hidden">
      <label for="radio1"><input name="radio1" type="radio" id="radio1" disabled style="display:none;"><span class="custom radio"></span> Radio Button 3</label>
    </div>

    <div class="form-actions">
      <button type="submit" class="btn">Search</button>
    </div>

  <% end %>
</div>